#include <stdio.h>                                                                                                                                                                                                      
#include <string.h>                                                                                                                                                                                                        
#include <stdint.h>                                                                                                                                                                                                        
void print_bin(char* str){                                                                                                                                                                                                 
        int i=0;                                                                                                                                                                                                           
        while(str[i]!=0){                                                                                                                                                                                                  
                printf("%c %hhu ", str[i], str[i]);                                                                                                                                                                        
                unsigned char ch=(unsigned char)str[i];                                                                                                                                                                    
                for(int j=7; j>=0; j--){                                                                                                                                                                                   
                        printf("%hhu",(ch >> j) & 1);                                                                                                                                                                      
                }                                                                                                                                                                                                          
                printf("\t%b", ch);                                                                                                                                                                                        
                printf("\n");                                                                                                                                                                                              
        i++;                                                                                                                                                                                                               
        }                                                                                                                                                                                                                  
}                                                                                                                                                                                                                          
                                                                                                                                                                                                                           
int main(int argc, char** argv){                                                                                                                                                                                           
        char* input2 = "🚀";                                                                                                                                                                                               
        printf("%s\t", input2);                                                                                                                                                                                            
        //char* input2 ="∫";                                                                                                                                                                                               
        for(int i=0; i< strlen(input2); i++){                                                                                                                                                                              
                printf("%b ", (unsigned char)input2[i]);                                                                                                                                                                   
        }                                                                                                                                                                                                                  
        printf("\n");                                                                                                                                                                                                      
        unsigned char* input = (unsigned char*)argv[1];                                                                                                                                                                    
        unsigned char c0 = (unsigned char)input[0];                                                                                                                                                                        
        print_bin(input);                                                                                                                                                                                                  
        if ((c0 & 0xE0) == 0xC0) {                                                                                                                                                                                         
                unsigned char c1 = (unsigned char)input[1];                                                                                                                                                                
                printf(("%b\n"),(unsigned char)((c0 & 0x1F) << 6 | (c1 & 0x3F)));                                                                                                                                          
                int32_t ret = (int32_t)(c0 & 0x1F) << 6 | (int32_t)(c1 & 0x3F);                                                                                                                                            
                printf("%d\n",ret);                                                                                                                                                                                        
        }                                                                                                                                                                                                                  
        else printf("%d\n",(int32_t)c0);                                                                                                                                                                                   
                                                                                                                                                                                                                           
}  
